version: "3.9"
services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    depends_on:
      - lavalink
      - postgres
    networks:
      - default
  lavalink:
    container_name: lavalink
    build:
      context: .
      dockerfile: Dockerfile
      target: lavalink
    networks:
      - default
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    environment:
      "POSTGRES_PASSWORD": xd
      "BOT_USER_NAME": bot
      "BOT_USER_PASSWORD": test
      "BOT_DATABASE_NAME": test
    networks:
      - default
  
networks:
  default: {
      external: true,
      internal: true
  }