#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER $BOT_USER_NAME WITH PASSWORD '$BOT_USER_PASSWORD';
	CREATE DATABASE $BOT_DATABASE_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $BOT_DATABASE_NAME TO $BOT_USER_NAME;
EOSQL